### ISSUE TITLE
Обновление до 16.5

### ISSUE THREAD

**Issue by pilezkiy** [matiaspub/bxApiDocs#13]
Обновиться пора. На дворе 16.5 :)
Могу файлы модулей от Б24 дать.

**Comment by egorzot** [comment]
Поддерживаю

**Comment by Arnavel** [comment]
+1

**Comment by hipot** [comment]
Серега, весь битрикс-мир ждет обновку)

**Comment by DmitryDmitrienko** [comment]
Плюсую :)

**Comment by vizh** [comment]
Да, было бы здорово!

**Comment by ArsenBespalov** [comment]
Когда уже автор репы обновит до 16 версии?
