### ISSUE TITLE
Static методы

### ISSUE THREAD

**Issue by victorlapshev** [matiaspub/bxApiDocs#17]
Как то вышло что много non-static методов в разных классах, стали static. Можно конечно вручную поправлять, я сейчас так и делаю и потом сделаю пулл, но может попробуем разобраться как они в процессе парсинга превратились в статичные?

**Comment by matiaspub** [comment]
этот момент мне предстоит переписывать при следующем обновлении,
я в старом ядре нахально всем ставлю static у кого $this внутри метода не используется
так как старое ядро поголовно все без каких либо модификаторов (под php4~) на что IDE ругается похлеще чем на non-static
к следующему релизу подумаю как решить этот вопрос, а пока терпим, ну или можно ручками править если сильно бесит

**Comment by victorlapshev** [comment]
понял, окей, ждемс
