### ISSUE TITLE
Проблема с кодировкой

### ISSUE THREAD

**Issue by art-zhitnik** [matiaspub/bxApiDocs#18]
Отличный инструмент! Поставил свежий Eclipse for PHP Developers Version: Neon.2 Release (4.6.2), [ломает гад кодировку](http://shot.qip.ru/00SNSA-62Q3rLszN/). Базовая кодировка у меня сейчас UTF-8 (Windows/Preferences/Workspace/Text file encoding; Project/Properties/Resource/Text file encoding). Работают в Win7.

**Comment by matiaspub** [comment]
https://github.com/matiaspub/bxApiDocs/issues/1 так попробуйте
иначе - открывайте Issue в репе Eclipse )
