### ISSUE TITLE
Будет ли обновление 17.0?

### ISSUE THREAD

**Issue by higimo** [matiaspub/bxApiDocs#23]
Сабж.

**Comment by victorlapshev** [comment]
Присоединяюсь, можем помочь с допилом парсера

**Comment by higimo** [comment]
Если потребуется — давайте через пулл-реквест это сделаем, просто дайте знать есть ли у вас в пранах заниматься этим.

**Comment by matiaspub** [comment]
Обновление в планах, сделать до конца года (если удастся выцепить новый синтаксис) ..
Структура сильно изменилась, прийдется полностью переписать парсер. Пока ждем или обновляем ручками, пул реквесты буду принимать в ветке **handjob**

**Comment by matiaspub** [comment]
теперь Проект обновляется посредством принятия пул-реквестов
