### ISSUE TITLE
Поддержка Composer

### ISSUE THREAD

**Issue by decadence** [matiaspub/bxApiDocs#24]
Здравствуйте, спасибо за вашу работу.

Может стоит добавить поддержку Composer? 
Это позволит ставить документацию в папку vendor (и тогда IDE автоматически ее бы индексировала) одной командой  или установить глобально в системе через composer global require. И упростит обновление.

Люди могут добавить либу в require-dev, чтобы документация устанавливалась только на дев-площадках.

**Comment by nook-ru** [comment]
Удалю свой [форк](https://packagist.org/packages/nook-ru/bx-api-docs#dev-master), когда будет оригинал

**Comment by decadence** [comment]
Шустро, спасибо)

**Comment by decadence** [comment]
Собственно, закрываю в пользу PR.

**Comment by matiaspub** [comment]
@nook-ru спасибо за активность
добавлю в README линк на ваш пакет

**Comment by matiaspub** [comment]
@nook-ru влил ваш пул
добавил на packagist matiaspub/bx-api-docs
